
name: Build

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Build Debs
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos $THEOS
          make fresh

      - name: Attach Debs To Release
        run: |
          export TAG="${GITHUB_REF#refs/tags/}"          
          gh release upload "$TAG" debs/*.deb
